
exp_name: MNIST_BABY

modules:
    model:
        name: mnist_classifier
        args:
            num_classes: 10

datasets:
    train:
        name: mnist
        args:
            root: '/local/debezenac/data/mnist'
            train: True
            download: True
            batch_size: &batch_size 22

    test:
        name: mnist
        args:
            root: '/local/debezenac/data/mnist'
            train: False
            download: True
            batch_size: *batch_size


trainer:
    name: classifier
    args:
        hello: 1

ngpu: 1
nepochs: 10