common: &common
    train: True
    batch_size:  16
    num_workers: 4
    shuffle: True
    drop_last: False

mnist: &mnist
    batch_size : 64
    root: '/local/debezenac/data/mnist'
    download: True
    <<: *common

fashion_mnist:
  <<: *mnist