
common: &common
  nepochs: 10
  verbose: 1
  use_tqdm: True



mnist:
    nepochs: 10
<<<<<<< HEAD:configs/default/experiment.yaml
    # niter:
    #   train: max
    #   val: 10
    <<: *common
=======
    niter:
      train: max
      val: 10
    <<: *common

unpaired:
  nepochs: 10
  niter:
    train: max
    val: 10
  <<: *common
>>>>>>> origin/arthur:default_configs/experiment.yaml
