modules:
    policy:
        _name: policy
        critic: true
        obs_size: 8
        action_size: 4

datasets:
    gym_env:
        _name: gym
        batch_size: 32
        id: LunarLander-v2

optimizers:
    optim:
        _name: adam
        _modules: policy
        lr: 0.03

experiment:
    _name: actor_critic
    gamma: 0.99
    device: cpu
    nepisodes: 1000000