modules:
    policy:
#        _name: classic
        _name: dynamic
        critic: true
        hidden_size: 64

datasets:
    gym_env:
#        _name: LunarLander
        _name: CartPole
        batch_size: 32

optimizers:
    optim:
        _name: adam
        _modules: policy
        lr: 0.001
#        weight_decay: 0.0001
        weight_decay: 0.0

experiment:
    _name: ac
    normalize_reward: false