modules:
    netG:
        _name: mnist_classifier
    netD:
        _name: mnist_classifier

datasets:
    trainset:
        _name: imagenet_tiny
        train: True
        batch_size: &batch_size 32
        corruption: &corruption
            name: remove_pix_dark
            percent: 0.90


    testset:
        _name: imagenet_tiny
        train: False
        batch_size: *batch_size
        corruption: *corruption


optimizers:
    netG_optim:
        _name: adam
        _modules: netG
        lr: 0.001

    netD_optim:
        _name: adam
        _modules: netD
        lr: 0.001

experiment:
    _name: unpaired
    nepochs: 10
    use_tqdm: True
    device: cuda