modules:
    model:
        _name: mnist_classifier

datasets:

    trainset:
        _name: mnist
        root: '/local/veniat/data/mnist'
        train: True
        batch_size: &batch_size 22

    testset:
        _name: mnist
        root: '/local/veniat/data/mnist'
        train: False
        batch_size: *batch_size

optimizers:
    optim:
        _name: sgd
        _modules: model
        lr: 0.001

experiment:
    _name: mnist_ignite
    device: cpu
    nepochs: 10