modules:
    model:
        _name: mnist_classifier

datasets:
    trainset:
        _name: mnist
        train: True
        batch_size: &batch_size 22

    testset:
        _name: mnist
        train: False
        batch_size: *batch_size

optimizers:
    optim:
        _name: sgd
        _modules: model
        lr: 0.001
        # scheduler:
        #     _name: exponential
        #     gamma: 0.99

experiment:
    _name: mnist
    nepochs: 10
    use_tqdm: True