modules:
    model:
        _name: mnist_classifier

datasets:
    train:
        _name: mnist
        train: True
        batch_size: &batch_size 22

    test:
        _name: mnist
        train: False
        batch_size: *batch_size

experiment:
    _name: mnist
    nepochs: 10
    lr: 0.0001
    use_tqdm: True